[project]
name = "drafter"
requires-python = ">=3.9"
license = {file = "LICENSE"}
readme = "README.md"
description = ""
authors = [
    {name = "Sidney Mau", email = "sidneymau@gmail.com" }
]
dynamic = ["version"]
dependencies = [
    "matplotlib",
    "numpy",
]
